baseURL = 'https://panchobarrerav.github.io/'
languageCode = 'en-us'
theme = 'graysx'
title = 'Telaio'

## Site Settings
[params]
logo = "assets/img/logo.webp"
favicon = "assets/favicon.png"

# Info
address = ""
email = "satoshi@nakamoto"
phone = "21.000.000"

# Socials

twitter = "#"
facebook = "#"
github = "#"

# Other

# Startbootstrap Contact Form Token https://startbootstrap.com/solution/contact-forms
sbtoken = "TOKEN_HERE"

## Menu Items
[menu]
  [[menu.main]]
  name = "About"
  URL = "#about"
  weight = 1

  [[menu.main]]
  name = "Projects"
  URL = "#projects"
  weight = 2

  [[menu.main]]
  name = "Contact"
  URL = "#signup"
  weight = 3